modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/GenerationsMod"
license = "Insert License Here"

[[mods]]
modId = "modulename"
version = "${version}"
displayName = "Generations ModuleName"
authors = "The Generations Team"
description = '''
'''
#logoFile = ""

[[dependencies.generations_modulename]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.generations_modulename]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.generations_modulename]]
modId = "generations_core"
mandatory = true
versionRange = "[)"
ordering = "BEFORE"
side = "BOTH"
